### PR TITLE
Backward compatibility import

### PR DESCRIPTION
**Pull request by FlorianDeconinck**
Refactor in the DSL port infrastructure lead to a change of import of the `geos_wrapper` code.
We introduce a backward compatible import to be able to cover both current and next version of the wrapper.

### CODE REVIEW

**Review by mathomp4 — APPROVED** [review]

**Comment by FlorianDeconinck** [comment]
Looks `gFTL` version issue on the CI, which is unrelated to the PR. Is there a branch I should merge in?

**Comment by mathomp4** [comment]
Ohh. Your CI is out of date. You might try updating the `.circleci/config.yml` to be like that in the mainline:

https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/blob/main/.circleci/config.yml

**Comment by mathomp4** [comment]
The issue now seems to be that you are missing some updates from this repo itself. This:
```
/root/project/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSsuperdyn_GridComp/@FVdycoreCubed_GridComp/StandAlone_FV3_Dycore.F90(18): error #6457: This derived type name has not been declared.   [MAPL_FLAPCLI]
   type (MAPL_FlapCLI) :: cli
---------^
```
is from old MAPL. We moved to fArgParse back in June:

https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/pull/208

**Review by tclune — APPROVED** [review]
cmake changes ok

**Pull request merged**
