### PR TITLE
Initialize uc and vc to 0 in the r8 version of computeMassFluxes in dev/MAPL-2.0

### LINKED ISSUE #7: Initialize uc and vc to 0 in fv_computeMassFluxesR8
This brings the r8 version in line with the r4 version and fixes a crash present when running the CTM.

### PR DESCRIPTION
**Pull request by kgerheiser**
This is required for the dev/MAPL-2.0 branch so that I can distribute my coupled CTM on Github and fixes #7 for that branch.

### CODE REVIEW

**Comment by mathomp4** [comment]
@kgerheiser Are these zero-diff? If so, we'll need a required label and, I suppose, someone to press the "Update branch" button below to make sure it has the latest code when merging.

**Comment by kgerheiser** [comment]
It is zero-diff

**Comment by wmputman** [comment]
Kyle updated this to using MAPL_UNDEF rather than 0s. That's when I approved it

**Comment by kgerheiser** [comment]
Forgot about this branch. Changed it to MAPL_UNDEF here too.

**Comment by mathomp4** [comment]
Whoops. I might have hand merged this in earlier today:
Screen Shot 2019-10-02 at 12 43 48 PM

As such I'll close as the code is now there

**Comment by mathomp4** [comment]
As proof:
https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/blob/cdf4aa1398a52465816673f7749b27f7a20f80b7/FV_StateMod.F90#L2915-L2917

**Pull request closed without merging**
