### PR TITLE
Refactor and update interp_restarts.x for new restart types

### PR DESCRIPTION
**Pull request by bena-nasa**
This is a refactoring of interp_restarts.x to support new restart types. GOCART2G will be producing restarts that have a "level" and an "ungridded dimension". In addition hemco now has a 2D-only restart. These are not currently supported. So I have done the following:
* Moved all routines needed for interp_restarts.x. to in this repo to make it easier to maintain
* Split interp_restarts.x into to programs, one for binary that really should not have to change ever as we are no longer using this in current and new systems, and another for NetCDF that I can focus on improving, cleaning, and adding new features as needed.
* Extended the NetCDF version so support the new kinds of restarts that will be coming with GOCART2G.

I have tested this for zero-diff, both both the binary and NetCDF versions with the existing restarts supported by both as well as made sure this works with the new GOCART2G restarts.

### CODE REVIEW

**Comment by mathomp4** [comment]
@bena-nasa Does this need edits anywhere else? Like in `regrid.pl`?

**Review by tclune — APPROVED** [review]
cmake changes ok

**Comment by bena-nasa** [comment]
That build failure for gfortran is in CARMAchem, not anywhere in the code I touched ....

**Comment by mathomp4** [comment]
> That build failure for gfortran is in CARMAchem, not anywhere in the code I touched ....

No, it looks like it's interp_restarts.F90:
```
[ 98%] Building Fortran object src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/GEOSCHEMchem_GridComp/CMakeFiles/GEOSCHEMchem_GridComp.dir/Chem_GridCompMod.F90.o
/root/project/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSsuperdyn_GridComp/@FVdycoreCubed_GridComp/interp_restarts.F90:612:79:

  612 |                call MAPL_IOChangeRes(InCfg(1),OutCfg(1),(/'lon ','lat ','lev ','unknown_dim1'/),(/imc,jmc,npz,rst_files(ifile)%ungrid_size/),rc=status)
      |                                                                               1
Error: Different CHARACTER lengths (4/12) in array constructor at (1)
```
I think you need to do something like:
```fortran
call MAPL_IOChangeRes(InCfg(1),OutCfg(1),[character(len=12):: 'lon ','lat ','lev ','unknown_dim1'],[imc,jmc,npz,rst_files(ifile)%ungrid_size],rc=status)
```

or you can pad out the others: `['lon         ','lat            ', ..."`

**Comment by bena-nasa** [comment]
> > That build failure for gfortran is in CARMAchem, not anywhere in the code I touched ....
> 
> No, it looks like it's interp_restarts.F90:
> 
> ```
> [ 98%] Building Fortran object src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/GEOSCHEMchem_GridComp/CMakeFiles/GEOSCHEMchem_GridComp.dir/Chem_GridCompMod.F90.o
> /root/project/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSsuperdyn_GridComp/@FVdycoreCubed_GridComp/interp_restarts.F90:612:79:
> 
>   612 |                call MAPL_IOChangeRes(InCfg(1),OutCfg(1),(/'lon ','lat ','lev ','unknown_dim1'/),(/imc,jmc,npz,rst_files(ifile)%ungrid_size/),rc=status)
>       |                                                                               1
> Error: Different CHARACTER lengths (4/12) in array constructor at (1)
> ```
> 
> I think you need to do something like:
> 
> ```fortran
> call MAPL_IOChangeRes(InCfg(1),OutCfg(1),[character(len=12):: 'lon ','lat ','lev ','unknown_dim1'],[imc,jmc,npz,rst_files(ifile)%ungrid_size],rc=status)
> ```
> 
> or you can pad out the others: `['lon ','lat ', ..."`

ah, that gfortran problem. I'll fix this, although I thought it was complaining about CARMAchem too, oh well.

**Comment by mathomp4** [comment]
> ah, that gfortran problem. I'll fix this, although I thought it was complaining about CARMAchem too, oh well.

Huh. I actually didn't look further down. I just stopped at the first I saw. Though, I hope there isn't a CARMAchem issue, that code hasn't changed in a while!

**Review by mathomp4 — APPROVED** [review]
We Trust in Ben!

**Pull request merged**
