### PR TITLE
Initialize uc and vc to 0d0 in computeMassFluxesR8

### LINKED ISSUE #7: Initialize uc and vc to 0 in fv_computeMassFluxesR8
This brings the r8 version in line with the r4 version and fixes a crash present when running the CTM.

### PR DESCRIPTION
**Pull request by kgerheiser**
This fixes #7 and is separate from my other PR which is for the dev/MAPL-2.0 branch while this is a hotfix for master.

Without this the CTM crashes, and this initialization is already present in the r4 version.

### CODE REVIEW

**Comment by wmputman** [comment]
Initializing these to 0 could be masking an error, can they be set to MAPL_UNDEF?

**Comment by kgerheiser** [comment]
I will try that

**Comment by kgerheiser** [comment]
@wmputman 

I can produce bitwise identical results initializing it to 0d0 or MAPL_UNDEF

**Comment by kgerheiser** [comment]
The reason it crashes with debug flags on is not because it actually uses the uninitialized value but because of the way the fv passes around arrays. 

In fv_computeMassFluxes_r8 `compute_utvt` takes an automatic 2d array, but `uc` is a 3d array and when the `compute_utvt`is called `uc` is passed as `uc(isd,jsd,k)`, not. Now, this is legal Fortran, but I think it confuses the uninitialized value checker in ifort.

**Comment by kgerheiser** [comment]
I have changed it so that they are set to MAPL_UNDEF

**Comment by mathomp4** [comment]
@kgerheiser It looks like this branch is out-of-date with `master`. I can press "Update branch" if you like or you can. If things look good then, I can approve and issue a new release.

**Comment by kgerheiser** [comment]
I've updated the branch

**Pull request merged**
