### PR TITLE
Modified conditional statements  to access AdvCore EXPORT pointers only when needed

### PR DESCRIPTION
**Pull request by JulesKouatchou**
- Modified the code so that up to the first ntracers advected tracers are passed to AdvCore EXPORT state. 
- The changes do not affect at all any CTM experiment. 
- The section of the code where the changes were made, is only use for diagnostics.

### CODE REVIEW

**Comment by mathomp4** [comment]
Okay. I can confirm this is zero-diff for the GEOSgcm when running in "regular" mode. The question is: would this affect @wmputman when he runs in mixed mode with AdvCore for moist tracers?

**Comment by mathomp4** [comment]
@bena-nasa can you look at this?

**Review by wmputman — APPROVED** [review]
Looks fine to me

**Comment by mathomp4** [comment]
Bill approves, so I will merge.

**Pull request merged**
