### PR TITLE
Squash unnecessary warning from FVdycore

### PR DESCRIPTION
**Pull request by sdeastham**
When the user does NOT want to exclude advection tracers, there is currently no way to safely ensure this without causing a warning to be pushed to stdout on every time step. This can now be prevented by setting `EXCLUDE_ADVECTION_TRACERS: NO` in the relevant resource file.

### CODE REVIEW

**Review by atrayano — APPROVED** [review]

**Comment by mathomp4** [comment]
@sdeastham It's annoying, but could you maybe base this against `develop`. This isn't really a hotfix, I suppose, so it should technically go to that first. Not that it matters much in the end

**Review by atrayano — APPROVED** [review]

**Comment by mathomp4** [comment]
Welp, the boring GEOSgcm model seems to run with this update. I suppose it is safe. I'll consult @tclune on what the correct version for the release should be...

**Comment by tclune** [comment]
Well, it is a new feature, however minor.  So in and of itself it suggest a minor revision.  

I think one of the struggles we have here, is that when features are accumulated by the in-house team, we don't feel pressured to make a release until something big comes along or we feel we have lots of little things worth capturing.  But when an external feature is submitted we feel pressured to do a new release right away.   Not saying that's good or bad.  Just an observation.

**Comment by mathomp4** [comment]
@tclune Okay. I don't mind. infinite number of integers! :)

**Review by mathomp4 — APPROVED** [review]
Seems to be safe. Approving.

**Comment by mathomp4** [comment]
@sdeastham I've released v1.7.0 with this fix.

**Pull request merged**
