### PR TITLE
Added "do k=1,npz" and "enddo" to the upper part of the if-else-endif…

### PR DESCRIPTION
**Pull request by aoloso**
… block below:

      tqtot = 0.0
      if ( (.not. ADIABATIC) .AND. (FV_Atm(1)%flagstruct%nwat /= 0) ) then
       if (FV_Atm(1)%flagstruct%nwat == 6) then
         do k=1,npz
            tqtot(:,:) = tqtot(:,:) + ( &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,sphu) + &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,qliq) + &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,qice) + &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,rain) + &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,snow) + &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,grpl) ) * FV_Atm(1)%delp(isc:iec,jsc:jec,k)
         enddo
       else
         do k=1,npz
            tqtot(:,:) = tqtot(:,:) + ( &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,sphu) + &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,qlcn) + &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,qlls) + &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,qicn) + &
            FV_Atm(1)%q(isc:iec,jsc:jec,k,qils) ) * FV_Atm(1)%delp(isc:iec,jsc:jec,k)
         enddo
       endif
      endif

### CODE REVIEW

**Comment by mathomp4** [comment]
Huh. That does seem a bug. If @wmputman agrees, we can get this in.

**Comment by atrayano** [comment]
The fix seems reasonable to me too. Looked like these was a bug before

**Review by wmputman — APPROVED** [review]

**Comment by wmputman** [comment]
Yes, it's a bug, fortunately we don't typically go down this path in the code.

**Comment by mathomp4** [comment]
Confirmed no difference with "standard" AMIP style runs. So, I'll merge and make a release.

**Pull request merged**
